# coding: utf-8

"""
    sundial

    Sundial optimises renewable power generation  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sundial
from sundial.models.one_of_plant_filter1_order import OneOfPlantFilter1Order  # noqa: E501
from sundial.rest import ApiException


class TestOneOfPlantFilter1Order(unittest.TestCase):
    """OneOfPlantFilter1Order unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfPlantFilter1Order(self):
        """Test OneOfPlantFilter1Order"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sundial.models.one_of_plant_filter1_order.OneOfPlantFilter1Order()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
