# coding: utf-8

"""
    sundial

    Sundial optimises renewable power generation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sundial
from sundial.api.plant_controller_api import PlantControllerApi  # noqa: E501
from sundial.rest import ApiException


class TestPlantControllerApi(unittest.TestCase):
    """PlantControllerApi unit test stubs"""

    def setUp(self):
        self.api = PlantControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_plant_controller_create(self):
        """Test case for plant_controller_create

        """
        pass

    def test_plant_controller_delete_by_id(self):
        """Test case for plant_controller_delete_by_id

        """
        pass

    def test_plant_controller_find(self):
        """Test case for plant_controller_find

        """
        pass

    def test_plant_controller_find_by_id(self):
        """Test case for plant_controller_find_by_id

        """
        pass

    def test_plant_controller_replace_by_id(self):
        """Test case for plant_controller_replace_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
