# coding: utf-8

"""
    sundial

    Sundial optimises renewable power generation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sundial
from sundial.api.advice_controller_api import AdviceControllerApi  # noqa: E501
from sundial.rest import ApiException


class TestAdviceControllerApi(unittest.TestCase):
    """AdviceControllerApi unit test stubs"""

    def setUp(self):
        self.api = AdviceControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_advice_controller_get_plant_advice(self):
        """Test case for advice_controller_get_plant_advice

        """
        pass


if __name__ == '__main__':
    unittest.main()
