# coding: utf-8

"""
    sundial

    Sundial optimises renewable power generation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sundial
from sundial.models.plant_filter1 import PlantFilter1  # noqa: E501
from sundial.rest import ApiException


class TestPlantFilter1(unittest.TestCase):
    """PlantFilter1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlantFilter1(self):
        """Test PlantFilter1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sundial.models.plant_filter1.PlantFilter1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
