# coding: utf-8

"""
    sundial

    Sundial optimises renewable power generation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sundial
from sundial.models.plant_fields import PlantFields  # noqa: E501
from sundial.rest import ApiException


class TestPlantFields(unittest.TestCase):
    """PlantFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlantFields(self):
        """Test PlantFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sundial.models.plant_fields.PlantFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
