# coding: utf-8

"""
    sundial

    Sundial optimises renewable power generation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sundial
from sundial.models.advice_recommendations import AdviceRecommendations  # noqa: E501
from sundial.rest import ApiException


class TestAdviceRecommendations(unittest.TestCase):
    """AdviceRecommendations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdviceRecommendations(self):
        """Test AdviceRecommendations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sundial.models.advice_recommendations.AdviceRecommendations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
